<div class="row justify-content-between align-items-center">
  <div class="col">
    <!-- <p class="fs-6 mb-0">&copy; <span class="d-none d-sm-inline-block"><?=date('Y')?> Śramani Institute, Inc. All rights reserved.Ecosymbionts all Regenerate Together ("EaRTh") is an initiative of the Śramani Institute and publishes each Contribution in accordance with a non-exclusive license to publish granted by the Author(s), who retain copyright to all components of their Contribution and who are responsible for the content, veracity, and originality of their Contribution. To the best of the knowledge of Ecosymbionts Regenerate, Ecosymbionts all Regenerate Together ("EaRTh"), and the Śramani Institute none of the content on this website is generated using Artificial Intelligence (AI). Ecosymbionts Regenerate, Ecosymbionts all Regenerate Together ("EaRTh"), and the Śramani Institute are not liable for the content of external sites or for the content of published Contributions generated by Authors.</span></p> -->
    <?=$generalSetting->footer_text?>
  </div>
</div>
<!-- End Row -->