<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul>
                    <li class="foot_logo"><a href="index.php"><img src="images/logo.webp" alt="" class="img-responsive"></a></li>
                    <li><a target="_blank" href="in-the-media.php" class="footer_btn">In The Media</a></li>
                    <li><a target="_blank" href="<?=$base_url?>earth" class="footer_btn_2">Online Platform</a></li>
                </ul>
                <div class="fot_smalltext">© 2024 Śramani Institute, Inc. All rights reserved. Ecosymbionts all Regenerate Together ("EaRTh") is an initiative of the Śramani Institute and publishes each Contribution in accordance with a non-exclusive license to publish granted by the Author(s), who retain copyright to all components of their Contribution and who are responsible for the content, veracity, and originality of their Contribution. To the best of the knowledge of Ecosymbionts Regenerate, Ecosymbionts all Regenerate Together ("EaRTh"), and the Śramani Institute none of the content on this website is generated using Artificial Intelligence (AI). Ecosymbionts Regenerate, Ecosymbionts all Regenerate Together ("EaRTh"), and the Śramani Institute are not liable for the content of external sites or for the content of published Contributions generated by Authors.</div>
                <div class="kelfot">
                    <a href="https://keylines.net/" target="_blank">Powered by Keyline</a>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- js link -->
<script src="js/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/multiselect-dropdown.js"></script>
<script src="js/audioplayer.js"></script>
<script>
    $(function() {
    $('audio').audioPlayer();
    });
</script>
<script>
    $('.panel-title > a').click(function() {
    $(this).parents('.panel-default').find('i').toggleClass('fa-plus fa-minus');
    $(this).parents('.panel-default').siblings('.panel-default').find('i').removeClass('fa-minus').addClass('fa-plus')

    });   
    
    $(window).scroll(function() {    
    var scroll = $(window).scrollTop();

    if (scroll >= 100) {
        $(".header_top").addClass("darkHeader");
    } else {
        $(".header_top").removeClass("darkHeader");
    }
});
</script>
</body>
</html>